--
-- 全局常量
-- Author: RedPig
-- Date: 2016/10/03
--

------[[声明全局常量]]----
	local TUNING = GLOBAL.TUNING
	--巨鹿生命值
	TUNING.DEERCLOPS_HEALTH = TUNING.DEERCLOPS_HEALTH * 2
	--巨鸭生命值
	TUNING.MOOSE_HEALTH = TUNING.MOOSE_HEALTH * 2
	--巨熊生命值
	TUNING.BEARGER_HEALTH = TUNING.BEARGER_HEALTH * 1
	--女武神初始物品
	TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WATHGRITHR = {"meat", "meat", "meat", "meat"}
	--维斯初始物品
	TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WES = {"tophat"}
	--温蒂初始物品
	--TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WENDY = {"abigail_flower", "pkc_livingstaff", "pkc_forgedarts", "pkc_blacksmith_edge", "pkc_infernalstaff"}
	--维斯伤害系数
	TUNING.WES_DAMAGE_MULT = 0.90
	--温蒂生命值
	TUNING.WENDY_HEALTH = TUNING.WILSON_HEALTH
	--阿比阿盖尔生命值
	TUNING.ABIGAIL_HEALTH = TUNING.WILSON_HEALTH * 4
	--读触手书消耗的脑残
	GLOBAL.READ_BOOK_TENTACLES_SANITY = 50
	--读催眠书消耗的脑残
	GLOBAL.READ_BOOK_SLEEP_SANITY = 20
	--秋天较长模式开关
	GLOBAL.PKC_IS_LONG_AUTUMN = GetModConfigData("is_long_autumn")
	if GLOBAL.PKC_IS_LONG_AUTUMN then
		TUNING.AUTUMN_LENGTH = 30
		TUNING.WINTER_LENGTH = 15
		TUNING.SPRING_LENGTH = 10
		TUNING.SUMMER_LENGTH = 5
		TUNING.SEASON_LENGTH_FRIENDLY_DEFAULT = 30
	end

	TUNING.THE_FORGE_ITEM_PACK = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DURABILITY = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DURABILITY.AMOUNT = 0
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DURABILITY.CONSUMPTION_NORMAL = 1
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DURABILITY.CONSUMPTION_SPECIAL = 5
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.COOLDOWN = 12
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DISABLE_RECIPE = false
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.DAMAGE = 30
	TUNING.THE_FORGE_ITEM_PACK.PKC_BLACKSMITH_EDGE.HELMSPLIT_DAMAGE = 100

	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DURABILITY = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DURABILITY.AMOUNT = 0
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DURABILITY.CONSUMPTION_NORMAL = 1
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DURABILITY.CONSUMPTION_SPECIAL = 5
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.COOLDOWN = 24
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.COOLDOWN = 24
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DURATION = 10
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.HEAL_RATE = 6
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DISABLE_RECIPE = false
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.DAMAGE = 10
	TUNING.THE_FORGE_ITEM_PACK.PKC_LIVINGSTAFF.SCALE_RNG = { 30, 40 }

	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DURABILITY = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DAMAGE = 20
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.COOLDOWN = 18
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DURABILITY.AMOUNT = 0
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DURABILITY.CONSUMPTION_NORMAL = 1
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DURABILITY.CONSUMPTION_SPECIAL = 5
	TUNING.THE_FORGE_ITEM_PACK.PKC_FORGEDARTS.DISABLE_RECIPE = false

	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DURABILITY = {}
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DURABILITY.AMOUNT = 0
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DURABILITY.CONSUMPTION_NORMAL = 1
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DURABILITY.CONSUMPTION_SPECIAL = 5
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.ALT_DAMAGE = { base = 200, center_mult = 0.25 }
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.COOLDOWN = 5
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DISABLE_RECIPE = false
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.DAMAGE = 25
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.ALT_DAMAGE.base = 200
	TUNING.THE_FORGE_ITEM_PACK.PKC_INFERNALSTAFF.ALT_RADIUS = 4.1

	--回城等待时间(秒)
	GLOBAL.GOHOME_WAIT_TIME = 10
	--回城精神消耗
	GLOBAL.GOHOME_SANITY_DELTA = 15
	--回城饥饿消耗
	GLOBAL.GOHOME_HUNGER_DELTA = 10
	--冲刺饥饿消耗
	GLOBAL.SPRINT_HUNGER_DELTA = 5
	--战斗猪人初始攻击力
	GLOBAL.PKC_PIGMAN_DAMAGE = TUNING.PIG_DAMAGE
	--战斗猪人初始生命值
	GLOBAL.PKC_PIGMAN_HEALTH = 400
	--战斗猪人初始攻击频率
	GLOBAL.PKC_PIGMAN_ATTACKPERIOD = 0.8 * TUNING.PIG_ATTACK_PERIOD
	--眼球塔攻击力
	GLOBAL.PKC_EYETURRET_DAMAGE = 50
	--眼球塔生命
	GLOBAL.PKC_EYETURRET_HEALTH = 1000
	--每队允许传送牌的数量
	GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM = 10
	GLOBAL.PKC_GROUPHOMESIGN_NUM = 10
	--猪王附近初始允许的最大猪房数量（猪房数会随着猪王等级而提升）
	GLOBAL.PKC_INIT_PIGHOUSE_NUM = 10
	--GLOBAL.PKC_MAX_PIGHOUSE_NUM = 10
	GLOBAL.PKC_HOST = "www.redpig666.com"

	--猪王等级对应数据
	GLOBAL.PIGKING_LEVEL_CONSTANT = {
		[1] = {LEVEL = 1, PIGKING_RANGE = 20, RANGE_SCALE = 1.75, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM},
		[2] = {LEVEL = 2, PIGKING_RANGE = 21, RANGE_SCALE = 1.80, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 1, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 1},
		[3] = {LEVEL = 3, PIGKING_RANGE = 22, RANGE_SCALE = 1.85, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 1, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 1},
		[4] = {LEVEL = 4, PIGKING_RANGE = 23, RANGE_SCALE = 1.90, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 2, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 2},
		[5] = {LEVEL = 5, PIGKING_RANGE = 24, RANGE_SCALE = 1.95, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 2, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 2},
		[6] = {LEVEL = 6, PIGKING_RANGE = 25, RANGE_SCALE = 2.00, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 3, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 3},
		[7] = {LEVEL = 7, PIGKING_RANGE = 26, RANGE_SCALE = 2.05, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 3, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 3},
		[8] = {LEVEL = 8, PIGKING_RANGE = 27, RANGE_SCALE = 2.10, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 4, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 4},
		[9] = {LEVEL = 9, PIGKING_RANGE = 28, RANGE_SCALE = 2.15, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 4, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 4},
		[10] = {LEVEL = 10, PIGKING_RANGE = 29, RANGE_SCALE = 2.15, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 5, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 5},
		[11] = {LEVEL = 11, PIGKING_RANGE = 30, RANGE_SCALE = 2.20, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 5, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 5},
		[12] = {LEVEL = 12, PIGKING_RANGE = 31, RANGE_SCALE = 2.25, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 6, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 6},
		[13] = {LEVEL = 13, PIGKING_RANGE = 32, RANGE_SCALE = 2.25, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 6, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 6},
		[14] = {LEVEL = 14, PIGKING_RANGE = 33, RANGE_SCALE = 2.30, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 7, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 7},
		[15] = {LEVEL = 15, PIGKING_RANGE = 34, RANGE_SCALE = 2.33, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 7, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 7},
		[16] = {LEVEL = 16, PIGKING_RANGE = 35, RANGE_SCALE = 2.35, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 8, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 8},
		[17] = {LEVEL = 17, PIGKING_RANGE = 36, RANGE_SCALE = 2.40, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 8, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 8},
		[18] = {LEVEL = 18, PIGKING_RANGE = 38, RANGE_SCALE = 2.45, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 9, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 9},
		[19] = {LEVEL = 19, PIGKING_RANGE = 45, RANGE_SCALE = 2.55, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 10, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 10},
		[20] = {LEVEL = 20, PIGKING_RANGE = 50, RANGE_SCALE = 2.65, PIGHOUSE_NUM = GLOBAL.PKC_INIT_PIGHOUSE_NUM + 10, HOMESING_NUM = GLOBAL.PKC_INIT_GROUPHOMESIGN_NUM + 10},
		--[1] = {LEVEL = 1, PIGKING_RANGE = 20, RANGE_SCALE = 1.75},
		--[2] = {LEVEL = 2, PIGKING_RANGE = 22, RANGE_SCALE = 1.85},
		--[3] = {LEVEL = 3, PIGKING_RANGE = 24, RANGE_SCALE = 1.95},
		--[4] = {LEVEL = 4, PIGKING_RANGE = 26, RANGE_SCALE = 2.05},
		--[5] = {LEVEL = 5, PIGKING_RANGE = 29, RANGE_SCALE = 2.15},
		--[6] = {LEVEL = 6, PIGKING_RANGE = 32, RANGE_SCALE = 2.25},
		--[7] = {LEVEL = 7, PIGKING_RANGE = 35, RANGE_SCALE = 2.35},
		--[8] = {LEVEL = 8, PIGKING_RANGE = 38, RANGE_SCALE = 2.45},
		--[9] = {LEVEL = 9, PIGKING_RANGE = 41, RANGE_SCALE = 2.55},
		--[10] = {LEVEL = 10, PIGKING_RANGE = 45, RANGE_SCALE = 2.65},
	}
